//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileGenerator.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TileGeneratorSoap")]
    public interface TileGeneratorSoap {
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTiles", ReplyAction="*")]
        TileGenerator.ServiceReference1.CreateTilesResponse CreateTiles(TileGenerator.ServiceReference1.CreateTilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTiles", ReplyAction="*")]
        System.Threading.Tasks.Task<TileGenerator.ServiceReference1.CreateTilesResponse> CreateTilesAsync(TileGenerator.ServiceReference1.CreateTilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTiles", Namespace="http://tempuri.org/", Order=0)]
        public TileGenerator.ServiceReference1.CreateTilesRequestBody Body;
        
        public CreateTilesRequest() {
        }
        
        public CreateTilesRequest(TileGenerator.ServiceReference1.CreateTilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destination;
        
        public CreateTilesRequestBody() {
        }
        
        public CreateTilesRequestBody(string url, string destination) {
            this.url = url;
            this.destination = destination;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TileGenerator.ServiceReference1.CreateTilesResponseBody Body;
        
        public CreateTilesResponse() {
        }
        
        public CreateTilesResponse(TileGenerator.ServiceReference1.CreateTilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateTilesResponseBody {
        
        public CreateTilesResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TileGeneratorSoapChannel : TileGenerator.ServiceReference1.TileGeneratorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TileGeneratorSoapClient : System.ServiceModel.ClientBase<TileGenerator.ServiceReference1.TileGeneratorSoap>, TileGenerator.ServiceReference1.TileGeneratorSoap {
        
        public TileGeneratorSoapClient() {
        }
        
        public TileGeneratorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TileGeneratorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TileGeneratorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TileGeneratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TileGenerator.ServiceReference1.CreateTilesResponse TileGenerator.ServiceReference1.TileGeneratorSoap.CreateTiles(TileGenerator.ServiceReference1.CreateTilesRequest request) {
            return base.Channel.CreateTiles(request);
        }
        
        public void CreateTiles(string url, string destination) {
            TileGenerator.ServiceReference1.CreateTilesRequest inValue = new TileGenerator.ServiceReference1.CreateTilesRequest();
            inValue.Body = new TileGenerator.ServiceReference1.CreateTilesRequestBody();
            inValue.Body.url = url;
            inValue.Body.destination = destination;
            TileGenerator.ServiceReference1.CreateTilesResponse retVal = ((TileGenerator.ServiceReference1.TileGeneratorSoap)(this)).CreateTiles(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TileGenerator.ServiceReference1.CreateTilesResponse> TileGenerator.ServiceReference1.TileGeneratorSoap.CreateTilesAsync(TileGenerator.ServiceReference1.CreateTilesRequest request) {
            return base.Channel.CreateTilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TileGenerator.ServiceReference1.CreateTilesResponse> CreateTilesAsync(string url, string destination) {
            TileGenerator.ServiceReference1.CreateTilesRequest inValue = new TileGenerator.ServiceReference1.CreateTilesRequest();
            inValue.Body = new TileGenerator.ServiceReference1.CreateTilesRequestBody();
            inValue.Body.url = url;
            inValue.Body.destination = destination;
            return ((TileGenerator.ServiceReference1.TileGeneratorSoap)(this)).CreateTilesAsync(inValue);
        }
    }
}
